# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "903404213a4ff47f7d851008d79ebf55"
name = "recora-engine"
handle = "recora-engine-new-123"
application_url = "https://occurs-mysimon-france-poetry.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_orders,read_products,read_themes,read_translations,unauthenticated_read_metaobjects,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_write_customers,write_inventory,write_locations,write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = ["https://occurs-mysimon-france-poetry.trycloudflare.com/auth/callback", "https://occurs-mysimon-france-poetry.trycloudflare.com/auth/shopify/callback", "https://occurs-mysimon-france-poetry.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
